# Database Initialization

In [2]:
import sqlite3
from ripe_wrapper.database.database_table import DatabaseTable
from ripe_wrapper.database.hop_result_detail_table import HopResultDetailTable
from ripe_wrapper.database.hop_result_table import HopResultTable
from ripe_wrapper.database.error_table import ErrorTable
from ripe_wrapper.database.txt_result_table import TxtResultTable
from ripe_wrapper.database.pseudosection_table import PseudosectionTable
from ripe_wrapper.database.measurement_probe_table import MeasurementProbeTable
from ripe_wrapper.database.result_table import ResultTable
from ripe_wrapper.database.probe_table import ProbeTable
from ripe_wrapper.database.measurement_table import MeasurementTable
from ripe_wrapper.database.tag_table import TagTable
from ripe_wrapper.database.autonomous_systems_table import AutonomousSystemsTable
from ripe_wrapper.database.request_table import RequestTable
from ripe_wrapper.database.request_pseudosection_table import RequestPseudosectionTable
import pandas as pd

In [11]:
DatabaseTable.DATABASE_PATH = "data/test.db"

In [12]:
request_table = RequestTable()
request_table.create_table()

In [12]:
request_pseudosection_table = RequestPseudosectionTable()
request_pseudosection_table.create_table()

In [10]:
txt_result_table = TxtResultTable()
txt_result_table.create_table()

In [11]:
pseudosection_table = PseudosectionTable()
pseudosection_table.create_table()

In [12]:
probe_table = ProbeTable()
probe_table.create_table()

In [13]:
measurement_table = MeasurementTable()
measurement_table.create_table()

In [14]:
tag_table = TagTable()
tag_table.create_table()

In [15]:
measurement_probe_table = MeasurementProbeTable()
measurement_probe_table.create_table()

In [16]:
result_table = ResultTable()
result_table.create_table()

In [17]:
error_table = ErrorTable() 
error_table.create_table()

In [18]:
hop_result_table = HopResultTable()
hop_result_table.create_table()

In [19]:
hop_result_detail_table = HopResultDetailTable()
hop_result_detail_table.create_table()

In [20]:
as_table = AutonomousSystemsTable()
as_table.create_table()

In [5]:
import csv 
import time
tsv_file = open("ip2asn-v4-u32.tsv")
read_tsv = csv.reader(tsv_file, delimiter="\t")
for row in read_tsv:
    item = {
        'number': row[2],
        'name': row[4]
    }
    filters = {'number': row[2]}
    if not as_table.exists(filters):
        try:
            as_table.add_item(item)
        except: 
            print(item)

{'number': '2187', 'name': "FR-SYVIK Reseau regional pour l?enseignement, la recherche et l'innovation en Normandie"}
{'number': '29007', 'name': "PETROTEL-AS Petrotel's commercial IP network Chemikow 7, Plock Poland"}
{'number': '26876', 'name': "CHICOS - chico's fas inc"}
{'number': '23256', 'name': "DAVIDSBRIDAL - David's Bridal"}
{'number': '15073', 'name': "CPS-197 - California Physicians' Service"}
{'number': '40026', 'name': "DCSG-NUM1 - DICK'S SPORTING GOODS INC"}
{'number': '40026', 'name': "DCSG-NUM1 - DICK'S SPORTING GOODS INC"}
{'number': '32834', 'name': "CHILDRENS-MEDICAL-CENTER - Children's Medical Center of Dallas"}
{'number': '11361', 'name': "BOSCOVS - Boscov's Department Store, LLC"}
{'number': '40026', 'name': "DCSG-NUM1 - DICK'S SPORTING GOODS INC"}
{'number': '40026', 'name': "DCSG-NUM1 - DICK'S SPORTING GOODS INC"}
{'number': '32197', 'name': "MEGUIARS-AS-PORT - Meguiar's Inc."}
{'number': '40233', 'name': "SLOM-INC - SLOMIN'S INC."}
{'number': '36111', 'name': "BRINKS-INC-INTERNET - Brink's, Inc."}
{'number': '36150', 'name': "SONICDRIVEIN - America's Drive-in Corp"}
{'number': '35910', 'name': "LOVES-TRAVEL-STOPS - Love's Travel Stops & Country Stores Inc."}
{'number': '23189', 'name': "OSAM - O'Shaughnessy Asset Management, LLC"}
{'number': '4057', 'name': "DCS-ASN - Mechant's Choice Payment Solutions"}
{'number': '36111', 'name': "BRINKS-INC-INTERNET - Brink's, Inc."}
{'number': '36111', 'name': "BRINKS-INC-INTERNET - Brink's, Inc."}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '32018', 'name': "MEGUIARS-AS - Meguiar's Inc."}
{'number': '394989', 'name': "GENES - Gene's Telecom"}
{'number': '396262', 'name': "FSO-ASN - Fresno County Sheriff's Office"}
{'number': '26720', 'name': "SCHAEFFERS-INVESTMENT-RESEARCH - Schaeffer's Investment Research"}
{'number': '33234', 'name': "SJOBERGS-INC - Sjoberg's Inc"}
{'number': '15013', 'name': "LMID - Fuss & O'Neill Technologies, LLC"}
{'number': '35910', 'name': "LOVES-TRAVEL-STOPS - Love's Travel Stops & Country Stores Inc."}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '394989', 'name': "GENES - Gene's Telecom"}
{'number': '54531', 'name': "LPCH-PA - LUCILE SALTER PACKARD CHILDREN'S HOSPITAL AT STANFORD"}
{'number': '18564', 'name': "SJU149068 - St. John's University, New York"}
{'number': '18564', 'name': "SJU149068 - St. John's University, New York"}
{'number': '394989', 'name': "GENES - Gene's Telecom"}
{'number': '11361', 'name': "BOSCOVS - Boscov's Department Store, LLC"}
{'number': '394877', 'name': "BCH - Blythedale Children's Hospital"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '59318', 'name': "SINET-KH SINET Fiber One, Cambodia's Fastest Broadband Service."}
{'number': '131207', 'name': "SINET-KH SINET, Cambodia's specialist Internet and Telecom Service Provider."}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '134544', 'name': "CENBONGT-AS-AP Cenbong Int'l Holdings Limited"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '132369', 'name': "HIEN-AS-AP Hien's Labs"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '29007', 'name': "PETROTEL-AS Petrotel's commercial IP network Chemikow 7, Plock Poland"}
{'number': '9551', 'name': "KMUTT-AP King Mongkut's University of Technology"}
{'number': '394121', 'name': "VCH-MADERA - Valley Children's Hospital"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '47198', 'name': "GENMAB Genmab's Corporate AS Number"}
{'number': '11716', 'name': "WON-AS - William O'Neil & Company"}
{'number': '32194', 'name': "ASN-PHOENIX-CHILDRENS - PHOENIX CHILDREN'S HOSPITAL"}
{'number': '393353', 'name': "ACUFCU - America's Credit Union"}
{'number': '40026', 'name': "DCSG-NUM1 - DICK'S SPORTING GOODS INC"}
{'number': '26876', 'name': "CHICOS - chico's fas inc"}
{'number': '23221', 'name': "JLBJH - JACK LINK'S BEEF JERKY"}
{'number': '14161', 'name': "LANDOLAKES - Land O'Lakes, Inc."}
{'number': '19356', 'name': "TOUA-NOC - Tohono O'Odham Utility Authority"}
{'number': '16384', 'name': "SMCVT - St Michael's College"}
{'number': '32873', 'name': "COG-ASN - Children's Oncology Group"}
{'number': '395618', 'name': "QUEENS-HEALTH-SYSTEM - The Queen's Medical Center"}
{'number': '33234', 'name': "SJOBERGS-INC - Sjoberg's Inc"}
{'number': '33234', 'name': "SJOBERGS-INC - Sjoberg's Inc"}
{'number': '132369', 'name': "HIEN-AS-AP Hien's Labs"}
{'number': '22844', 'name': "TRADERJOE - TRADER JOE'S COMPANY"}
{'number': '32834', 'name': "CHILDRENS-MEDICAL-CENTER - Children's Medical Center of Dallas"}
{'number': '46361', 'name': "GILLETTE-CHILDRENS-SPECIALTY-HEALTHCARE - Gillette Children's Specialty Healthcare"}
{'number': '35856', 'name': "LWCC - Louisiana Workers' Compensation Corporation"}
{'number': '36111', 'name': "BRINKS-INC-INTERNET - Brink's, Inc."}
{'number': '40026', 'name': "DCSG-NUM1 - DICK'S SPORTING GOODS INC"}
{'number': '11716', 'name': "WON-AS - William O'Neil & Company"}
{'number': '22130', 'name': "DAS-BGP-29 - Doctor's Associates Inc."}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '18784', 'name': "MCD-US-ASN - McDonald's Corporation"}
{'number': '18784', 'name': "MCD-US-ASN - McDonald's Corporation"}
{'number': '32022', 'name': "CHC-AS - Children's Hospital Colorado"}
{'number': '32022', 'name': "CHC-AS - Children's Hospital Colorado"}
{'number': '40026', 'name': "DCSG-NUM1 - DICK'S SPORTING GOODS INC"}
{'number': '11255', 'name': "SBT-NET - Screamin' Banshee Technologies"}
{'number': '395188', 'name': "SALADASN-01 - Saladino's Inc."}
{'number': '395188', 'name': "SALADASN-01 - Saladino's Inc."}
{'number': '53662', 'name': "COLLIER-COUNTY-SHERIFFS-OFFICE - Collier County Sheriff's Office"}
{'number': '19600', 'name': "NCH-AS - Nationwide Children's Hospital"}
{'number': '394262', 'name': "GLWD-AS - God's Love We Deliver, Inc."}
{'number': '22844', 'name': "TRADERJOE - TRADER JOE'S COMPANY"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '53621', 'name': "RADY-CHILDRENS-HOSPITAL-SAN-DIEGO - Rady Children's Hospital - San Diego"}
{'number': '40026', 'name': "DCSG-NUM1 - DICK'S SPORTING GOODS INC"}
{'number': '33234', 'name': "SJOBERGS-INC - Sjoberg's Inc"}
{'number': '33234', 'name': "SJOBERGS-INC - Sjoberg's Inc"}
{'number': '33234', 'name': "SJOBERGS-INC - Sjoberg's Inc"}
{'number': '32194', 'name': "ASN-PHOENIX-CHILDRENS - PHOENIX CHILDREN'S HOSPITAL"}
{'number': '36823', 'name': "MPHC - Martin's Point HealthCare"}
{'number': '26122', 'name': "SJHHC-ASN - St. Joseph's Hospital Health Center"}

{'number': '16778', 'name': "CCHCS-2-ASN-1 - Cook Children's Health Care System"}
{'number': '30881', 'name': "TENSOR-AS Yaroslavl' branch"}
{'number': '29007', 'name': "PETROTEL-AS Petrotel's commercial IP network Chemikow 7, Plock Poland"}
{'number': '204708', 'name': "MDW-MAIN-AS The main Autonomous System of Midway's Network (Belfort, France)."}
{'number': '30881', 'name': "TENSOR-AS Yaroslavl' branch"}
{'number': '30881', 'name': "TENSOR-AS Yaroslavl' branch"}
{'number': '39694', 'name': "I-CIF Credit Immobillier de France's IT division"}
{'number': '39694', 'name': "I-CIF Credit Immobillier de France's IT division"}
{'number': '30881', 'name': "TENSOR-AS Yaroslavl' branch"}
{'number': '8901', 'name': "Moscow Mayor's Office"}
{'number': '208058', 'name': "VTELEKOME Network Project's Team"}
{'number': '39727', 'name': "ZZI-AS ZZI's AS Number"}
{'number': '48703', 'name': "CNAM-AS CNAM - AS de la Caisse Nationale d'Assurance Maladie"}
{'number': '208058', 'name': "VTELEKOME Network Project's Team"}
{'number': '8901', 'name': "Moscow Mayor's Office"}
{'number': '8901', 'name': "Moscow Mayor's Office"}
{'number': '30881', 'name': "TENSOR-AS Yaroslavl' branch"}
{'number': '30881', 'name': "TENSOR-AS Yaroslavl' branch"}
{'number': '30881', 'name': "TENSOR-AS Yaroslavl' branch"}
{'number': '131207', 'name': "SINET-KH SINET, Cambodia's specialist Internet and Telecom Service Provider."}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '33234', 'name': "SJOBERGS-INC - Sjoberg's Inc"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '55894', 'name': "WHOSNEXT Who's Next"}
{'number': '132309', 'name': "SIXYS-NETPOINT-AS-AP 6Y'S Pty Ltd"}
{'number': '132309', 'name': "SIXYS-NETPOINT-AS-AP 6Y'S Pty Ltd"}
{'number': '19993', 'name': "RJOBRIEN - R.J. O'Brien and Associates, Inc."}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '132326', 'name': "F1CSB-NET-MY K-7-10, No. 2 Jalan Solaris, Solaris Mon't Kiara"}
{'number': '136560', 'name': "MCDAPASN01-AS-AP McDonald's Corporation"}
{'number': '140890', 'name': "SAMLOW-APNIC-AS-AP McDonald's Corporation"}
{'number': '131207', 'name': "SINET-KH SINET, Cambodia's specialist Internet and Telecom Service Provider."}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '132862', 'name': "ST-AS-AP ST. LUKE'S MEDICAL CENTER (GLOBAL CITY), INC."}
{'number': '132246', 'name': "ST-AS-AP ST. LUKE'S MEDICAL CENTER, INC."}
{'number': '134544', 'name': "CENBONGT-AS-AP Cenbong Int'l Holdings Limited"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '63950', 'name': "JWNPL-AS-AP Jackie's Wholesale Nurseries Pty Ltd"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '132037', 'name': "HTCL-AS-AP HO'NGSA' TELECOM COMPANY LIMITED"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '135637', 'name': "PROFESSIONALS-AS-AP Haseeb Istiaqur Rahman t/a Professionals' Systems"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '134826', 'name': "SOFTDEBUTCOLTD-AS-AP Softde'but Co.,LTD."}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '136912', 'name': "KINGS-AS-AP THE COUNCIL OF THE KING'S SCHOOL"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '137390', 'name': "AUSRL-AS-AP Scott's Refrigerated Freightways PTY LTD"}
{'number': '139780', 'name': "BIC-AS-AP Brother's ICT Connectivity"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '131626', 'name': "NSS-GROUP-AS-TW NSS INT'L CO., LTD."}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '131626', 'name': "NSS-GROUP-AS-TW NSS INT'L CO., LTD."}
{'number': '139747', 'name': "CCI-AS-AP Children's Cancer Institute Australia"}
{'number': '139756', 'name': "MERREDINWIRELESS-AS-AP CHRIS'S TV AND SATELLITE"}
{'number': '139780', 'name': "BIC-AS-AP Brother's ICT Connectivity"}
{'number': '139815', 'name': "TUSB-AS-AP Taylor's University Sdn Bhd"}
{'number': '139959', 'name': "IDNIC-UPNVJ-AS-ID Universitas Pembangunan Nasional 'Veteran' Jakarta"}
{'number': '132369', 'name': "HIEN-AS-AP Hien's Labs"}
{'number': '141402', 'name': "SAC-AS-AP St Augustine's College-Sydney"}
{'number': '141432', 'name': "TZEES-AS-AP Tzee's Multi Services (Pvt.) Limited"}
{'number': '132104', 'name': "KRYPTO-AS-AP 27B, Jalan SS4D/2, People's Park, Petaling Jaya, Selangor 47301"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '135165', 'name': "LOAPL-AS-AP Laing O'Rourke Australia Pty Ltd"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '11756', 'name': "CHLA - Children's Hospital Los Angeles"}
{'number': '11756', 'name': "CHLA - Children's Hospital Los Angeles"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '13844', 'name': "SJRH - St. John's Riverside Hospital"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '30881', 'name': "TENSOR-AS Yaroslavl' branch"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '55846', 'name': "BBN-AS-AP IMED, Ministry of Planning, Government of the People's Republic of Bangladesh"}

{'number': '24353', 'name': "CNGI-XA-IX-AS-AP CERNET2 IX at Xi'an Jiaotong University"}
{'number': '139874', 'name': "WCNTCL-AS-AP Wu'an Chihong Network Technology Co., Ltd."}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '135637', 'name': "PROFESSIONALS-AS-AP Haseeb Istiaqur Rahman t/a Professionals' Systems"}
{'number': '141432', 'name': "TZEES-AS-AP Tzee's Multi Services (Pvt.) Limited"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '45189', 'name': "SYSTEM3-NET-IN INDIA'S ONLY CARRIER NEUTRAL DATA CENTRE"}
{'number': '9464', 'name': "PSU-TH-AS-AP Prince of Songkla University (Sritrang'NET)"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '132309', 'name': "SIXYS-NETPOINT-AS-AP 6Y'S Pty Ltd"}
{'number': '132309', 'name': "SIXYS-NETPOINT-AS-AP 6Y'S Pty Ltd"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '31983', 'name': "QUEENSU-KINGSTON - Queen's University"}
{'number': '31983', 'name': "QUEENSU-KINGSTON - Queen's University"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '204543', 'name': "FHRNET Filip Hruska's Experimental Network"}
{'number': '131207', 'name': "SINET-KH SINET, Cambodia's specialist Internet and Telecom Service Provider."}
{'number': '131207', 'name': "SINET-KH SINET, Cambodia's specialist Internet and Telecom Service Provider."}
{'number': '131207', 'name': "SINET-KH SINET, Cambodia's specialist Internet and Telecom Service Provider."}
{'number': '131207', 'name': "SINET-KH SINET, Cambodia's specialist Internet and Telecom Service Provider."}
{'number': '59318', 'name': "SINET-KH SINET Fiber One, Cambodia's Fastest Broadband Service."}
{'number': '131207', 'name': "SINET-KH SINET, Cambodia's specialist Internet and Telecom Service Provider."}
{'number': '131207', 'name': "SINET-KH SINET, Cambodia's specialist Internet and Telecom Service Provider."}
{'number': '40327', 'name': "GMHC-AS - GAY MEN'S HEALTH CRISIS, INC."}
{'number': '396087', 'name': "SMCM - St. Mary's College of Maryland"}
{'number': '17350', 'name': "KMV-LLC - Moody's KMV"}
{'number': '17350', 'name': "KMV-LLC - Moody's KMV"}
{'number': '17350', 'name': "KMV-LLC - Moody's KMV"}
{'number': '17350', 'name': "KMV-LLC - Moody's KMV"}
{'number': '46163', 'name': "ASNPTCFTC - Moody's Investors Service"}
{'number': '46163', 'name': "ASNPTCFTC - Moody's Investors Service"}
{'number': '46163', 'name': "ASNPTCFTC - Moody's Investors Service"}
{'number': '46163', 'name': "ASNPTCFTC - Moody's Investors Service"}
{'number': '46163', 'name': "ASNPTCFTC - Moody's Investors Service"}
{'number': '17350', 'name': "KMV-LLC - Moody's KMV"}
{'number': '17350', 'name': "KMV-LLC - Moody's KMV"}
{'number': '17350', 'name': "KMV-LLC - Moody's KMV"}
{'number': '46163', 'name': "ASNPTCFTC - Moody's Investors Service"}
{'number': '395126', 'name': "BECKS - Beck's Superior Hybrids, Inc."}
{'number': '822', 'name': "STJOSEPHS-AS - St. Joseph's Health Care, London"}
{'number': '396486', 'name': "CECCE - Conseil scolaire de district catholique du Centre-Est de l'Ontario"}
{'number': '822', 'name': "STJOSEPHS-AS - St. Joseph's Health Care, London"}
{'number': '40723', 'name': "UVA-WISE-AS - The University of Virginia's College at Wise"}
{'number': '19600', 'name': "NCH-AS - Nationwide Children's Hospital"}
{'number': '1265', 'name': "SAINT-MARYS-AS - Saint Mary's College"}
{'number': '1265', 'name': "SAINT-MARYS-AS - Saint Mary's College"}
{'number': '1265', 'name': "SAINT-MARYS-AS - Saint Mary's College"}
{'number': '396148', 'name': "DADDARIO - D'Addario & Company Inc."}
{'number': '395607', 'name': "CASEYS-CORP - Casey's Retail Company"}
{'number': '18564', 'name': "SJU149068 - St. John's University, New York"}
{'number': '18564', 'name': "SJU149068 - St. John's University, New York"}
{'number': '18564', 'name': "SJU149068 - St. John's University, New York"}
{'number': '18564', 'name': "SJU149068 - St. John's University, New York"}
{'number': '18564', 'name': "SJU149068 - St. John's University, New York"}
{'number': '18564', 'name': "SJU149068 - St. John's University, New York"}
{'number': '40385', 'name': "SAINT-MARYS-CA-AS - Saint Mary's College of California"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '46780', 'name': "SJUCSB-AS - Saint John's University - College of Saint Benedict"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '134175', 'name': "SH2206-AP UNIT A17,9/F SILVERCORP INT'L TOWER 707-713 NATHAN RD"}
{'number': '2602', 'name': "RESTENA Reseau Teleinformatique de l'Education Nationale"}
{'number': '7328', 'name': "CHOP - The Children's Hospital of Philadelphia"}
{'number': '7328', 'name': "CHOP - The Children's Hospital of Philadelphia"}
{'number': '7328', 'name': "CHOP - The Children's Hospital of Philadelphia"}
{'number': '7328', 'name': "CHOP - The Children's Hospital of Philadelphia"}
{'number': '7328', 'name': "CHOP - The Children's Hospital of Philadelphia"}
{'number': '7328', 'name': "CHOP - The Children's Hospital of Philadelphia"}
{'number': '30459', 'name': "AS-SLHC - St. Luke's Roosevelt Hospital Center"}
{'number': '133077', 'name': "SCHNEIDER-AS-HK 13/F East Wing, Warwick House, Taikoo Place, 979 King's Road, Quarry Bay, Hong Kong"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '14503', 'name': "HOOVERS - Hoover's, Inc."}
{'number': '9486', 'name': "KMITL-AP King Mongkut's Institute of Technology Ladkrabang"}
{'number': '33467', 'name': "SJRMC-NJ - St. Joseph's Medical Center"}
{'number': '132369', 'name': "HIEN-AS-AP Hien's Labs"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '15073', 'name': "CPS-197 - California Physicians' Service"}
{'number': '15073', 'name': "CPS-197 - California Physicians' Service"}
{'number': '3525', 'name': "ALBERTSONS - Albertson's Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}
{'number': '21789', 'name': "168-244 - Lowe's Companies, Inc."}

{'number': '3525', 'name': "ALBERTSONS - Albertson's Inc."}
{'number': '3525', 'name': "ALBERTSONS - Albertson's Inc."}
{'number': '4057', 'name': "DCS-ASN - Mechant's Choice Payment Solutions"}
{'number': '394521', 'name': "SMH-91-WTBY-CT - Saint Mary's Hospital, Inc."}
{'number': '53662', 'name': "COLLIER-COUNTY-SHERIFFS-OFFICE - Collier County Sheriff's Office"}
{'number': '32198', 'name': "MEGUIARS-AS-NASH - Meguiar's Inc."}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '14161', 'name': "LANDOLAKES - Land O'Lakes, Inc."}
{'number': '14161', 'name': "LANDOLAKES - Land O'Lakes, Inc."}
{'number': '8901', 'name': "Moscow Mayor's Office"}
{'number': '45953', 'name': "CNAPOPS-AS-AP Catholic Network Australia Limited (Common PoP's)"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '59318', 'name': "SINET-KH SINET Fiber One, Cambodia's Fastest Broadband Service."}
{'number': '131207', 'name': "SINET-KH SINET, Cambodia's specialist Internet and Telecom Service Provider."}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '394668', 'name': "STMARYSMEDICALCENTER-2900 - St. Mary's Medical Center, Inc."}
{'number': '36111', 'name': "BRINKS-INC-INTERNET - Brink's, Inc."}
{'number': '29007', 'name': "PETROTEL-AS Petrotel's commercial IP network Chemikow 7, Plock Poland"}
{'number': '42570', 'name': "EU-CH-KS_PORTSCANNING This ASN is used for Internet security research. Internet-scale port scanning activities are launched from it. Don't hesitate to contact portscan@nagra.com would you have any question."}
{'number': '49206', 'name': "PeakFactory, a MSP on IPTV, OTT and VOD with it's own CDN"}
{'number': '201621', 'name': "VGNET-AS VAUDOISE GENERALE, Compagnie d'Assurances SA"}
{'number': '2602', 'name': "RESTENA Reseau Teleinformatique de l'Education Nationale"}
{'number': '8901', 'name': "Moscow Mayor's Office"}
{'number': '16778', 'name': "CCHCS-2-ASN-1 - Cook Children's Health Care System"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '393555', 'name': "MOIT - City of Baltimore, Mayor's Office of Information Technology"}
{'number': '63151', 'name': "CPSL-ASN - The Children's Place"}
{'number': '3785', 'name': "ASN1 - Dr. Leonard's Healthcare Corp."}
{'number': '3785', 'name': "ASN1 - Dr. Leonard's Healthcare Corp."}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '15228', 'name': "OREILLYMEDIA-AS1 - O'Reilly Media, Inc."}
{'number': '393765', 'name': "MVHS - Faxton St Luke's Healthcare"}
{'number': '26723', 'name': "SJCRH - St. Jude Children's Research Hospital"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '16384', 'name': "SMCVT - St Michael's College"}
{'number': '393862', 'name': "CHILDRENSOMAHA - Children's Hospital & Medical Center"}
{'number': '2187', 'name': "FR-SYVIK Reseau regional pour l?enseignement, la recherche et l'innovation en Normandie"}
{'number': '2187', 'name': "FR-SYVIK Reseau regional pour l?enseignement, la recherche et l'innovation en Normandie"}
{'number': '9464', 'name': "PSU-TH-AS-AP Prince of Songkla University (Sritrang'NET)"}
{'number': '395277', 'name': "ST-LUKES-HOSPITAL - St. Luke's Hospital"}
{'number': '2602', 'name': "RESTENA Reseau Teleinformatique de l'Education Nationale"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '22721', 'name': "SPC-12 - Saint Peter's University"}
{'number': '393825', 'name': "BOZZ-275-CT - Bozzuto's Incorporated"}
{'number': '26012', 'name': "NET-OHIO-BWC - Ohio Bureau of Worker's Compensation"}
{'number': '32834', 'name': "CHILDRENS-MEDICAL-CENTER - Children's Medical Center of Dallas"}
{'number': '26633', 'name': "TEXAS-WOMANS-UNIVERSITY - Texas Woman's University"}
{'number': '394121', 'name': "VCH-MADERA - Valley Children's Hospital"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '10221', 'name': "HEWLETT-PACKARD Multi-homed connections to multiple ISP's providing"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '26394', 'name': "CHOA - Egleston Children's Hospital"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '30545', 'name': "LANDUSCOOPERATIVE - Farmer's Cooperative Company"}
{'number': '2470', 'name': "FR-LAREUNION Ile de la Reunion Departement d'Outre-Mer"}
{'number': '2470', 'name': "FR-LAREUNION Ile de la Reunion Departement d'Outre-Mer"}
{'number': '2470', 'name': "FR-LAREUNION Ile de la Reunion Departement d'Outre-Mer"}
{'number': '2470', 'name': "FR-LAREUNION Ile de la Reunion Departement d'Outre-Mer"}
{'number': '2602', 'name': "RESTENA Reseau Teleinformatique de l'Education Nationale"}
{'number': '2602', 'name': "RESTENA Reseau Teleinformatique de l'Education Nationale"}
{'number': '2602', 'name': "RESTENA Reseau Teleinformatique de l'Education Nationale"}
{'number': '2470', 'name': "FR-LAREUNION Ile de la Reunion Departement d'Outre-Mer"}
{'number': '2470', 'name': "FR-LAREUNION Ile de la Reunion Departement d'Outre-Mer"}
{'number': '2470', 'name': "FR-LAREUNION Ile de la Reunion Departement d'Outre-Mer"}
{'number': '2470', 'name': "FR-LAREUNION Ile de la Reunion Departement d'Outre-Mer"}
{'number': '764', 'name': "FI-PMO-AS Prime Minister's Office"}
{'number': '2470', 'name': "FR-LAREUNION Ile de la Reunion Departement d'Outre-Mer"}
{'number': '2470', 'name': "FR-LAREUNION Ile de la Reunion Departement d'Outre-Mer"}
{'number': '47301', 'name': "XTBPL-AS X-Trade Broker's AS Number"}
{'number': '2470', 'name': "FR-LAREUNION Ile de la Reunion Departement d'Outre-Mer"}
{'number': '19993', 'name': "RJOBRIEN - R.J. O'Brien and Associates, Inc."}
{'number': '40340', 'name': "PFCHANG - P. F. Chang's China Bistro, Inc."}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '11493', 'name': "HILLSBOROUGH-COUNTY-SHERIFFS-OFFICE - Hillsborough County Sheriff's Office"}
{'number': '8037', 'name': "PUB-BGP-AS - People's United Bank"}
{'number': '8037', 'name': "PUB-BGP-AS - People's United Bank"}

{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '26633', 'name': "TEXAS-WOMANS-UNIVERSITY - Texas Woman's University"}
{'number': '32873', 'name': "COG-ASN - Children's Oncology Group"}
{'number': '19421', 'name': "LANDSEND - Lands' End, Inc."}
{'number': '26633', 'name': "TEXAS-WOMANS-UNIVERSITY - Texas Woman's University"}
{'number': '26633', 'name': "TEXAS-WOMANS-UNIVERSITY - Texas Woman's University"}
{'number': '11716', 'name': "WON-AS - William O'Neil & Company"}
{'number': '11493', 'name': "HILLSBOROUGH-COUNTY-SHERIFFS-OFFICE - Hillsborough County Sheriff's Office"}
{'number': '11493', 'name': "HILLSBOROUGH-COUNTY-SHERIFFS-OFFICE - Hillsborough County Sheriff's Office"}
{'number': '11716', 'name': "WON-AS - William O'Neil & Company"}
{'number': '11716', 'name': "WON-AS - William O'Neil & Company"}
{'number': '33085', 'name': "THE-MENS-WEARHOUSE - The Men's Wearhouse"}
{'number': '27227', 'name': "DILLARDS-STORE-SERVICES - Dillard's Store Services Inc."}
{'number': '19993', 'name': "RJOBRIEN - R.J. O'Brien and Associates, Inc."}
{'number': '19993', 'name': "RJOBRIEN - R.J. O'Brien and Associates, Inc."}
{'number': '15228', 'name': "OREILLYMEDIA-AS1 - O'Reilly Media, Inc."}
{'number': '6061', 'name': "OREILLYMEDIA-AS2 - O'Reilly Media, Inc."}
{'number': '40026', 'name': "DCSG-NUM1 - DICK'S SPORTING GOODS INC"}
{'number': '27192', 'name': "COLI-NET - Chain O' Lakes Internet"}
{'number': '54531', 'name': "LPCH-PA - LUCILE SALTER PACKARD CHILDREN'S HOSPITAL AT STANFORD"}
{'number': '3411', 'name': "SMH-ASN - St. Michael's Hospital"}
{'number': '3411', 'name': "SMH-ASN - St. Michael's Hospital"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '32006', 'name': "HBC - Hudson's Bay Company"}
{'number': '32006', 'name': "HBC - Hudson's Bay Company"}
{'number': '393302', 'name': "SJC-AN - St. John's College"}
{'number': '394989', 'name': "GENES - Gene's Telecom"}
{'number': '132369', 'name': "HIEN-AS-AP Hien's Labs"}
{'number': '26633', 'name': "TEXAS-WOMANS-UNIVERSITY - Texas Woman's University"}
{'number': '395156', 'name': "THE-KINGS-UNIVERSITY - The King's University"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '46157', 'name': "MACS-CS-INC - Mac's Convenience Stores Inc."}
{'number': '13374', 'name': "DYC-DYU - D'Youville College"}
{'number': '13930', 'name': "CMH - The Children's Mercy Hospital"}
{'number': '3411', 'name': "SMH-ASN - St. Michael's Hospital"}
{'number': '3411', 'name': "SMH-ASN - St. Michael's Hospital"}
{'number': '11716', 'name': "WON-AS - William O'Neil & Company"}
{'number': '58418', 'name': "COUNSELS-CHAMBERS-AS-AP Counsel's Chambers Limited"}
{'number': '55563', 'name': "DR-NETWORK-IN Dr.Reddy's Laboratories Ltd."}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '9464', 'name': "PSU-TH-AS-AP Prince of Songkla University (Sritrang'NET)"}
{'number': '9533', 'name': "KMITNB-AS-AP King Mongkut's Institute of Technology North Bangkok"}
{'number': '9551', 'name': "KMUTT-AP King Mongkut's University of Technology"}
{'number': '9533', 'name': "KMITNB-AS-AP King Mongkut's Institute of Technology North Bangkok"}
{'number': '9464', 'name': "PSU-TH-AS-AP Prince of Songkla University (Sritrang'NET)"}
{'number': '9551', 'name': "KMUTT-AP King Mongkut's University of Technology"}
{'number': '9533', 'name': "KMITNB-AS-AP King Mongkut's Institute of Technology North Bangkok"}
{'number': '55918', 'name': "VISTAAR-SYSTEMS-IN Ground Floor, 'A' Wing"}
{'number': '24353', 'name': "CNGI-XA-IX-AS-AP CERNET2 IX at Xi'an Jiaotong University"}
{'number': '24353', 'name': "CNGI-XA-IX-AS-AP CERNET2 IX at Xi'an Jiaotong University"}
{'number': '24353', 'name': "CNGI-XA-IX-AS-AP CERNET2 IX at Xi'an Jiaotong University"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '17625', 'name': "BLAZENET-IN-AP BlazeNet's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '45117', 'name': "INPL-IN-AP Ishan's Network"}
{'number': '10221', 'name': "HEWLETT-PACKARD Multi-homed connections to multiple ISP's providing"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '136392', 'name': "SVHM-AS-AP ST. VINCENT'S HOSPITAL (MELBOURNE) LIMITED"}
{'number': '17632', 'name': "BCLNET-AS-AU Barristers Chambers' Limited"}
{'number': '24069', 'name': "STAPLES-AS-AP 163 O'Riordan Street Mascot"}
{'number': '140639', 'name': "PYMBLELADIES-NON-AS-AP Pymble Ladies' College"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '23686', 'name': "ASN-EQIX-MEL-EE-AP Equinix's Melbourne Peering Exchange"}
{'number': '137400', 'name': "PLCS-AS-AP Presbyterian Ladies' College Sydney"}
{'number': '24184', 'name': "GOVERNMENT-NETWORK-MALDIVES National Centre for Information Technology, Male', Maldives"}
{'number': '45533', 'name': "CGD-AS-TH-AP Comptroller General's Department"}
{'number': '45189', 'name': "SYSTEM3-NET-IN INDIA'S ONLY CARRIER NEUTRAL DATA CENTRE"}
{'number': '45189', 'name': "SYSTEM3-NET-IN INDIA'S ONLY CARRIER NEUTRAL DATA CENTRE"}
{'number': '17632', 'name': "BCLNET-AS-AU Barristers Chambers' Limited"}
{'number': '131207', 'name': "SINET-KH SINET, Cambodia's specialist Internet and Telecom Service Provider."}
{'number': '17350', 'name': "KMV-LLC - Moody's KMV"}
{'number': '17350', 'name': "KMV-LLC - Moody's KMV"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '11435', 'name': "LA-CAPITALE - La Capitale, cie d'assurance generale"}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '33159', 'name': "NSPNET1 - Nature's Sunshine Products, Inc."}
{'number': '11255', 'name': "SBT-NET - Screamin' Banshee Technologies"}
{'number': '26876', 'name': "CHICOS - chico's fas inc"}
{'number': '11716', 'name': "WON-AS - William O'Neil & Company"}
{'number': '11716', 'name': "WON-AS - William O'Neil & Company"}
{'number': '35910', 'name': "LOVES-TRAVEL-STOPS - Love's Travel Stops & Country Stores Inc."}
{'number': '395519', 'name': "AS-CTCHILDRENS - Connecticut Children's Medical Center"}
{'number': '26394', 'name': "CHOA - Egleston Children's Hospital"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}

{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '11015', 'name': "TCH-AS - Texas Children's Hospital"}
{'number': '55139', 'name': "LDRY - Landry's, Inc."}
{'number': '30369', 'name': "KEMI - Kentucky Employers' Mutual Insurance"}
{'number': '17270', 'name': "NYSTRS-AS1 - New York State Teachers' Retirement System"}
{'number': '26394', 'name': "CHOA - Egleston Children's Hospital"}
{'number': '22130', 'name': "DAS-BGP-29 - Doctor's Associates Inc."}
{'number': '14161', 'name': "LANDOLAKES - Land O'Lakes, Inc."}
{'number': '46361', 'name': "GILLETTE-CHILDRENS-SPECIALTY-HEALTHCARE - Gillette Children's Specialty Healthcare"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '40340', 'name': "PFCHANG - P. F. Chang's China Bistro, Inc."}
{'number': '11255', 'name': "SBT-NET - Screamin' Banshee Technologies"}
{'number': '11255', 'name': "SBT-NET - Screamin' Banshee Technologies"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '46654', 'name': "OC-INTERNET - O'Charleys Inc."}
{'number': '46654', 'name': "OC-INTERNET - O'Charleys Inc."}
{'number': '11255', 'name': "SBT-NET - Screamin' Banshee Technologies"}
{'number': '11255', 'name': "SBT-NET - Screamin' Banshee Technologies"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '11255', 'name': "SBT-NET - Screamin' Banshee Technologies"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '376', 'name': "RISQ-AS - Reseau d'informations scientifiques du Quebec (RISQ)"}
{'number': '11015', 'name': "TCH-AS - Texas Children's Hospital"}
{'number': '22844', 'name': "TRADERJOE - TRADER JOE'S COMPANY"}
{'number': '36546', 'name': "OREILLYAUTO - O'Reilly Automotive Inc."}
{'number': '19345', 'name': "SIMONS-ROCK-EDU-ASN01 - Bard College at Simon's Rock"}
{'number': '15013', 'name': "LMID - Fuss & O'Neill Technologies, LLC"}
{'number': '15013', 'name': "LMID - Fuss & O'Neill Technologies, LLC"}
{'number': '32284', 'name': "CORP-BASHAS-AS1 - Bashas' Inc."}
{'number': '32284', 'name': "CORP-BASHAS-AS1 - Bashas' Inc."}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '46443', 'name': "CFE-AS - Central Florida Educators' Federal Credit Union"}
{'number': '33234', 'name': "SJOBERGS-INC - Sjoberg's Inc"}
{'number': '33234', 'name': "SJOBERGS-INC - Sjoberg's Inc"}
{'number': '395126', 'name': "BECKS - Beck's Superior Hybrids, Inc."}
{'number': '11255', 'name': "SBT-NET - Screamin' Banshee Technologies"}
{'number': '11255', 'name': "SBT-NET - Screamin' Banshee Technologies"}
{'number': '11255', 'name': "SBT-NET - Screamin' Banshee Technologies"}
{'number': '3785', 'name': "ASN1 - Dr. Leonard's Healthcare Corp."}
{'number': '19969', 'name': "JOESDATACENTER - Joe's Datacenter, LLC"}
{'number': '395193', 'name': "WESTFIELD-INSURANCE - Ohio Farmer's Insurance Company"}
{'number': '132369', 'name': "HIEN-AS-AP Hien's Labs"}

{'number': '8901', 'name': "Moscow Mayor's Office"}
{'number': '8901', 'name': "Moscow Mayor's Office"}
{'number': '8901', 'name': "Moscow Mayor's Office"}
{'number': '40026', 'name': "DCSG-NUM1 - DICK'S SPORTING GOODS INC"}
{'number': '19993', 'name': "RJOBRIEN - R.J. O'Brien and Associates, Inc."}
{'number': '32873', 'name': "COG-ASN - Children's Oncology Group"}
{'number': '13877', 'name': "WENDYS-DUBLIN - Wendy's International, Inc."}
{'number': '13877', 'name': "WENDYS-DUBLIN - Wendy's International, Inc."}
{'number': '13877', 'name': "WENDYS-DUBLIN - Wendy's International, Inc."}
{'number': '40113', 'name': "SLHS-AS - ST. LUKE'S HEALTH SYSTEM, LTD."}
{'number': '40113', 'name': "SLHS-AS - ST. LUKE'S HEALTH SYSTEM, LTD."}
{'number': '40113', 'name': "SLHS-AS - ST. LUKE'S HEALTH SYSTEM, LTD."}
{'number': '40113', 'name': "SLHS-AS - ST. LUKE'S HEALTH SYSTEM, LTD."}
{'number': '33234', 'name': "SJOBERGS-INC - Sjoberg's Inc"}
{'number': '27192', 'name': "COLI-NET - Chain O' Lakes Internet"}
{'number': '29007', 'name': "PETROTEL-AS Petrotel's commercial IP network Chemikow 7, Plock Poland"}
{'number': '24353', 'name': "CNGI-XA-IX-AS-AP CERNET2 IX at Xi'an Jiaotong University"}
{'number': '24353', 'name': "CNGI-XA-IX-AS-AP CERNET2 IX at Xi'an Jiaotong University"}
{'number': '45189', 'name': "SYSTEM3-NET-IN INDIA'S ONLY CARRIER NEUTRAL DATA CENTRE"}

In [44]:
import pandas as pd
con = sqlite3.connect('ripe_results.db', timeout=60)

query = "SELECT * FROM measurements where type = 'traceroute' and af = 4 and probes_requested < 2447"
results = pd.read_sql(query, con)
results

,af,creation_time,description,group_id,id,participant_count,port,probes_requested,probes_scheduled,protocol,query_argument,query_class,query_type,resolve_on_probe,start_time,stop_time,target,type,udp_payload_size,use_probe_resolver
0,4,1640094219,Traceroute/IPv4/4/probe-resolver-request-all-p...,34570581,34570581,7,80,7,7,ICMP,None,None,None,False,1640094219,1640094603,1.0.0.1,traceroute,None,None
1,4,1640094220,Traceroute/IPv4/4/probe-resolver-request-all-p...,34570582,34570582,2,80,2,2,ICMP,None,None,None,False,1640094220,1640094603,1.1.1.2,traceroute,None,None
2,4,1640094221,Traceroute/IPv4/4/probe-resolver-request-all-p...,34570583,34570583,4,80,4,4,ICMP,None,None,None,False,1640094221,1640094603,1.1.1.3,traceroute,None,None
3,4,1640094222,Traceroute/IPv4/4/probe-resolver-request-all-p...,34570584,34570584,1,80,1,1,ICMP,None,None,None,False,1640094222,1640094603,100.100.0.100,traceroute,None,None
4,4,1640094225,Traceroute/IPv4/4/probe-resolver-request-all-p...,34570586,34570586,1,80,1,1,ICMP,None,None,None,False,1640094225,1640094603,100.100.100.200,traceroute,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,4,1640094881,Traceroute/IPv4/4/probe-resolver-request-all-p...,34571238,34571238,1,80,1,1,ICMP,None,None,None,False,1640094881,1640095204,90.155.52.250,traceroute,None,None
217,4,1640094882,Traceroute/IPv4/4/probe-resolver-request-all-p...,34571239,34571239,1,80,1,1,ICMP,None,None,None,False,1640094882,1640095204,92.220.228.70,traceroute,None,None
218,4,1640094883,Traceroute/IPv4/4/probe-resolver-request-all-p...,34571240,34571240,1,80,1,1,ICMP,None,None,None,False,1640094883,1640095204,96.22.246.145,traceroute,None,None
219,4,1640094885,Traceroute/IPv4/4/probe-resolver-request-all-p...,34571241,34571241,1,80,1,1,ICMP,None,None,None,False,1640094885,1640095204,96.76.225.35,traceroute,None,None
220,4,1640094886,Traceroute/IPv4/4/probe-resolver-request-all-p...,34571242,34571242,1,80,1,1,ICMP,None,None,None,False,1640094886,1640095204,97.75.167.168,traceroute,None,None

In [12]:
import sqlite3
import pandas as pd
conn = sqlite3.connect('ripe_results.db', timeout=60)
results = pd.read_sql("SELECT r.af, m.af, m.target, m.use_probe_resolver FROM  measurements m JOIN results r ON r.msm_id = m.id WHERE r.af != m.af and r.af != 0", conn)

In [13]:
results

        af  af target use_probe_resolver
0        6   4   None               True
1        6   4   None               True
2        6   4   None               True
3        6   4   None               True
4        6   4   None               True
...     ..  ..    ...                ...
150704   4   6   None               True
150705   4   6   None               True
150706   4   6   None               True
150707   4   6   None               True
150708   4   6   None               True

[150709 rows x 4 columns]

In [14]:
results[results["use_probe_resolver"] == "True"]

        af  af target use_probe_resolver
0        6   4   None               True
1        6   4   None               True
2        6   4   None               True
3        6   4   None               True
4        6   4   None               True
...     ..  ..    ...                ...
150704   4   6   None               True
150705   4   6   None               True
150706   4   6   None               True
150707   4   6   None               True
150708   4   6   None               True

[150709 rows x 4 columns]

In [28]:
conn = sqlite3.connect('ripe_results.db', timeout=60)
results = pd.read_sql("SELECT r.af, m.af as msm_af, m.target, m.use_probe_resolver, p.id FROM  measurements m JOIN results r ON r.msm_id = m.id JOIN probes p ON r.prb_id = p.id WHERE m.af = 6 and p.continent_code = 'AF'", conn)

In [30]:
results[results["use_probe_resolver"] == "None"].groupby(["target", "id"], as_index=False).size()

                  target     id  size
0   2001:4860:4860::8888  12466   140
1   2001:4860:4860::8888  14691    80
2   2001:4860:4860::8888  28607   140
3   2001:4860:4860::8888  55130   140
4   2001:4860:4860::8888  55146   140
5   2001:4860:4860::8888  55381   140
6        2001:67c:28a4::  12466   140
7        2001:67c:28a4::  14691    80
8        2001:67c:28a4::  28607   140
9        2001:67c:28a4::  55130   140
10       2001:67c:28a4::  55146   140
11       2001:67c:28a4::  55381   140
12  2606:4700:4700::1111  12466   140
13  2606:4700:4700::1111  14691    80
14  2606:4700:4700::1111  28607   140
15  2606:4700:4700::1111  55130   140
16  2606:4700:4700::1111  55146   140
17  2606:4700:4700::1111  55381   140
18       2620:119:35::35  12466   140
19       2620:119:35::35  14691    80
20       2620:119:35::35  28607   140
21       2620:119:35::35  55130   140
22       2620:119:35::35  55146   140
23       2620:119:35::35  55381   140
24       2620:74:1b::1:1  12466   140
25       2620:74:1b::1:1  14691    80
26       2620:74:1b::1:1  28607   140
27       2620:74:1b::1:1  55130   140
28       2620:74:1b::1:1  55146   140
29       2620:74:1b::1:1  55381   140
30           2620:fe::fe  12466   140
31           2620:fe::fe  14691    80
32           2620:fe::fe  28607   139
33           2620:fe::fe  55130   140
34           2620:fe::fe  55146   140
35           2620:fe::fe  55381   140
36     2a02:6b8::feed:ff  12466   140
37     2a02:6b8::feed:ff  14691    80
38     2a02:6b8::feed:ff  28607   140
39     2a02:6b8::feed:ff  55130   140
40     2a02:6b8::feed:ff  55146   140
41     2a02:6b8::feed:ff  55381   140
42       2a05:dfc7:5::53  12466   140
43       2a05:dfc7:5::53  14691    80
44       2a05:dfc7:5::53  28607   140
45       2a05:dfc7:5::53  55130   140
46       2a05:dfc7:5::53  55146   140
47       2a05:dfc7:5::53  55381   140
48         2a0d:2a00:1::  12466   140
49         2a0d:2a00:1::  14691    80
50         2a0d:2a00:1::  28607   140
51         2a0d:2a00:1::  55130   139
52         2a0d:2a00:1::  55146   140
53         2a0d:2a00:1::  55381   140

In [25]:
results[results["use_probe_resolver"] != "None"]

      af  msm_af target use_probe_resolver
1079   4       6   None               True
1080   4       6   None               True
1081   4       6   None               True
1082   4       6   None               True
1083   4       6   None               True
...   ..     ...    ...                ...
7793   4       6   None               True
7794   4       6   None               True
7795   4       6   None               True
7796   4       6   None               True
7797   4       6   None               True

[780 rows x 4 columns]

In [11]:
conn = sqlite3.connect('ripe_results_txt.db', timeout=60)
results = pd.read_sql("SELECT * FROM results", conn)
results

,rt,size,sub_id,sub_max,msm_id,prb_id,ancount,qdcount,nscount,arcount,...,abuf,result_id,lts,dst_addr,dst_port,src_addr,af,proto,udp_size,return_code
0,591.62,358,1,1,34856460,12894,1,1,0,1,...,SIKBgAABAAEAAAABBTEyODk0CjE2NDI1ODM3NTcLbWVtYn...,18562,346,1.1.1.1,53,10.0.2.16,4,UDP,1232,NOERROR
1,31.269,344,1,1,34856460,10001,1,1,0,1,...,hQaBgAABAAEAAAABBTEwMDAxCjE2NDI1ODM3NjkLbWVtYn...,34054,7,1.1.1.1,53,192.168.178.30,4,UDP,1232,NOERROR
2,32.731,344,1,1,34856460,10006,1,1,0,1,...,ZzKBgAABAAEAAAABBTEwMDA2CjE2NDI1ODM3NjULbWVtYn...,26418,42,1.1.1.1,53,192.168.1.137,4,UDP,1232,NOERROR
3,29.466,366,1,1,34856460,10015,1,1,0,1,...,nJGBgAABAAEAAAABBTEwMDE1CjE2NDI1ODM3NjYLbWVtYn...,40081,43,1.1.1.1,53,192.168.178.39,4,UDP,1232,NOERROR
4,29.146,345,1,1,34856460,10022,1,1,0,1,...,9TyBgAABAAEAAAABBTEwMDIyCjE2NDI1ODM3NjQLbWVtYn...,62780,0,1.1.1.1,53,10.71.6.153,4,UDP,1232,NOERROR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
400279,1343.385,394,1,2,34860762,10497,1,1,0,1,...,59yBgAABAAEAAAABBTEwNDk3CjE2NDI2MTc5MzkLbWVtYn...,59356,8,185.180.100.65,53,100.100.172.250,4,UDP,4096,NOERROR
400280,None,None,1,2,34860763,10120,None,None,None,None,...,None,None,255,192.168.88.1,53,None,4,TCP,None,None
400281,None,None,1,2,34860763,10141,None,None,None,None,...,None,None,15,192.168.1.164,53,None,4,TCP,None,None
400282,125.058,372,2,3,34860763,10159,1,1,0,1,...,SveBgAABAAEAAAABBTEwMTU5CjE2NDI2MTc5NTgLbWVtYn...,19191,32,193.68.138.10,53,193.68.138.19,4,TCP,1232,NOERROR
400283,37.733,366,1,1,34860764,10134,1,1,0,1,...,63OBgAABAAEAAAABBTEwMTM0CjE2NDI2MTc5MzkLbWVtYn...,60275,10,2606:4700:4700::1111,53,2a02:8010:64d4:12:a2f3:c1ff:fec4:48f8,6,UDP,1232,NOERROR

In [8]:
conn = sqlite3.connect('ripe_results.db', timeout=60)
results = pd.read_sql("SELECT * FROM results", conn)
results

,rt,size,sub_id,sub_max,msm_id,prb_id,ancount,qdcount,nscount,arcount,...,abuf,result_id,lts,dst_addr,dst_port,src_addr,af,proto,udp_size,return_code
0,14.29,55,1,1,34569793,52824,1,1,0,1,...,NxaBgAABAAEAAAABBmdvb2dsZQNjb20AAAEAAcAMAAEAAQ...,14102,2,1.1.1.1,53,10.1.4.109,4,UDP,1232,NOERROR
1,18.524,55,1,1,34569793,52827,1,1,0,1,...,oBCBgAABAAEAAAABBmdvb2dsZQNjb20AAAEAAcAMAAEAAQ...,40976,32,1.1.1.1,53,192.168.107.100,4,UDP,1232,NOERROR
2,25.889,55,1,1,34569793,52828,1,1,0,1,...,xI6BgAABAAEAAAABBmdvb2dsZQNjb20AAAEAAcAMAAEAAQ...,50318,20,1.1.1.1,53,172.16.24.21,4,UDP,1232,NOERROR
3,18.151,55,1,1,34569793,52844,1,1,0,1,...,arqBgAABAAEAAAABBmdvb2dsZQNjb20AAAEAAcAMAAEAAQ...,27322,33,1.1.1.1,53,192.168.0.241,4,UDP,1232,NOERROR
4,13.137,55,1,1,34569793,52849,1,1,0,1,...,QiOBgAABAAEAAAABBmdvb2dsZQNjb20AAAEAAcAMAAEAAQ...,16931,31,1.1.1.1,53,192.168.1.170,4,UDP,1232,NOERROR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5141537,3.408,55,1,2,34656464,53961,1,1,0,1,...,lKiBgAABAAEAAAABBmdvb2dsZQNjb20AAAEAAcAMAAEAAQ...,38056,19,109.194.112.1,53,10.200.202.10,4,TCP,4096,NOERROR
5141538,113.673,135,1,2,34656464,54550,6,1,0,1,...,kneBgAABAAYAAAABBmdvb2dsZQNjb20AAAEAAcAMAAEAAQ...,37495,60,8.8.8.8,53,10.10.10.10,4,TCP,512,NOERROR
5141539,90.623,55,2,3,34656464,54778,1,1,0,1,...,rq+BgAABAAEAAAABBmdvb2dsZQNjb20AAAEAAcAMAAEAAQ...,44719,15,9.9.9.11,53,172.24.5.253,4,TCP,1232,NOERROR
5141540,5.855,55,1,2,34656464,54983,1,1,0,1,...,N2aBgAABAAEAAAABBmdvb2dsZQNjb20AAAEAAcAMAAEAAQ...,14182,37,114.114.114.114,53,192.168.30.143,4,TCP,4096,NOERROR
5141541,None,None,1,2,34656464,55776,None,None,None,None,...,None,None,3,192.168.29.1,53,None,4,TCP,None,None

In [47]:
from ripe_wrapper.measurements.resolvers import RESOLVER_ADDRESSES
top_resolvers = results[~results['target'].isin(RESOLVER_ADDRESSES)]

In [48]:
top_resolvers = top_resolvers.groupby("target", as_index = False).size().sort_values("size")
top_resolvers[top_resolvers["size"] > 10]

                          target  size
198                 84.116.46.22    11
191                80.67.188.188    11
177                 66.209.192.5    11
214                90.155.52.250    11
215                92.220.228.70    11
183                  75.75.75.75    11
218                96.22.246.145    11
0                        1.0.0.1    11
170                 62.2.216.156    11
76            2001:41d0:3:163::1    11
75   2001:2003:f535:fd00::53:314    11
74             2001:148f:fffe::1    11
69                199.168.90.119    11
68                   195.84.96.4    11
64                 195.130.131.4    11
62                 195.130.131.1    11
59                  195.121.1.34    11
57                194.239.134.83    11
53                  194.109.6.66    11
42                  190.160.0.15    11
31                 181.213.132.3    11
30                 179.191.90.20    11
29               178.250.208.135    11
27                   172.64.36.1    11
21                  156.154.70.3    11
19               148.122.164.253    11
6                 100.100.105.90    11
1                        1.1.1.2    11
77          2001:470:64df:111::1    11
175                 64.59.160.14    11
80          2001:470:b1b7:103::1    11
86                2001:8b0::2020    11
165                54.254.156.43    11
152                 44.44.117.10    11
143           2a01:728:108:10::1    11
140                   2620:fe::9    11
134                23.233.128.16    11
133                 23.132.96.20    11
132              219.106.231.122    11
130              217.237.150.205    11
129              217.237.149.142    11
127                  217.0.43.81    11
119              213.209.104.220    11
113                 212.45.45.45    11
219                 96.76.225.35    11
108                212.27.40.240    11
106                 212.23.6.100    11
103                212.134.0.129    11
96                208.67.220.220    11
94               206.248.154.170    11
92                   202.74.33.0    11
82          2001:4860:4860::8844    11
220                97.75.167.168    11

In [19]:
import sqlite3
import pandas as pd


conn = sqlite3.connect('ripe_results.db')
con_new = sqlite3.connect('ripe_results_fallback.db')



df = pd.read_sql("SELECT * FROM autonomous_systems", conn)
df.to_sql(name='autonomous_systems', con=con_new)

con_new.commit()

con_new.close()
conn.close()

In [20]:
con_new = sqlite3.connect('ripe_results_fallback.db')

pd.read_sql("SELECT * FROM autonomous_systems", con_new)

       index      number                                               name
0          0           0                                         Not routed
1          1           1              LVLT-1 - Level 3 Communications, Inc.
2          2           2                  UDEL-DCN - University of Delaware
3          3           3  MIT-GATEWAYS - Massachusetts Institute of Tech...
4          4           4         ISI-AS - University of Southern California
...      ...         ...                                                ...
72209  72209  4294901921                                       AS4294901921
72210  72210  4294901922                                       AS4294901922
72211  72211  4294901926                                       AS4294901926
72212  72212  4294901929                                       AS4294901929
72213  72213  4294901930                                       AS4294901930

[72214 rows x 3 columns]

In [14]:
results = pd.read_sql("SELECT * FROM autonomous_systems", conn)
results

           number                                               name
0               0                                         Not routed
1               1              LVLT-1 - Level 3 Communications, Inc.
2               2                  UDEL-DCN - University of Delaware
3               3  MIT-GATEWAYS - Massachusetts Institute of Tech...
4               4         ISI-AS - University of Southern California
...           ...                                                ...
72209  4294901921                                       AS4294901921
72210  4294901922                                       AS4294901922
72211  4294901926                                       AS4294901926
72212  4294901929                                       AS4294901929
72213  4294901930                                       AS4294901930

[72214 rows x 2 columns]

In [80]:
# test txt measurment 9: > 4KB
# test txt measurment 8: ~2KB
conn = sqlite3.connect('fallback_test.db', timeout=60)
results = pd.read_sql("SELECT * FROM results", conn)
results

,rt,size,sub_id,sub_max,msm_id,prb_id,ancount,qdcount,nscount,arcount,...,abuf,result_id,lts,dst_addr,dst_port,src_addr,af,proto,udp_size,return_code
0,267.857,68,1,1,38427658,10001,0,1,0,1,...,x/ODgAABAAAAAAABBTEwMDAxCjE2NDQ1ODExNTgLbWVtYn...,51187,32,1.1.1.1,53,192.168.178.30,4,UDP,1232,NOERROR
1,310.04,68,1,1,38427658,10006,0,1,0,1,...,HcWDgAABAAAAAAABBTEwMDA2CjE2NDQ1ODExNTgLbWVtYn...,7621,36,1.1.1.1,53,192.168.1.137,4,UDP,1232,NOERROR
2,275.566,68,1,1,38427658,10015,0,1,0,1,...,KduDgAABAAAAAAABBTEwMDE1CjE2NDQ1ODExNTYLbWVtYn...,10715,38,1.1.1.1,53,192.168.178.39,4,UDP,1232,NOERROR
3,136.479,68,1,1,38427658,10022,0,1,0,1,...,pCCDgAABAAAAAAABBTEwMDIyCjE2NDQ1ODExNTcLbWVtYn...,42016,29,1.1.1.1,53,10.71.6.153,4,UDP,1232,NOERROR
4,190.697,68,1,1,38427658,10046,0,1,0,1,...,MIuDgAABAAAAAAABBTEwMDQ2CjE2NDQ1ODExNTcLbWVtYn...,12427,33,1.1.1.1,53,192.168.42.45,4,UDP,1232,NOERROR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7657,None,None,1,3,38428310,12438,None,None,None,None,...,None,None,36,fe80::a63e:51ff:fe1e:5d5b,53,None,6,TCP,None,None
7658,None,None,3,3,38428310,12454,None,None,None,None,...,None,None,75,192.168.50.1,53,2001:470:1f1b:e0:a2f3:c1ff:fec4:5e7b,4,TCP,None,None
7659,None,None,1,3,38428310,12466,None,None,None,None,...,None,None,44,10.1.254.254,53,None,4,TCP,None,None
7660,None,None,2,2,38428310,12501,None,None,None,None,...,None,None,18,10.0.0.1,53,2a02:908:1984:adb0:a2f3:c1ff:fec4:49ca,4,TCP,None,None
7661,None,None,1,3,38428310,12503,None,None,None,None,...,None,None,26,46.19.96.50,53,None,4,TCP,None,None

In [14]:
conn = sqlite3.connect('fallback_test_1.db', timeout=60)
results = pd.read_sql("SELECT * FROM results", conn)
results

,rt,size,sub_id,sub_max,msm_id,prb_id,ancount,qdcount,nscount,arcount,...,result_id,lts,dst_addr,dst_port,src_addr,af,proto,udp_size,return_code,question_name
0,139.741,68,1,1,38994801,10001,0,1,0,1,...,6599,46,1.1.1.1,53,192.168.178.30,4,UDP,1232,NOERROR,10001.1645522518.membrain-it.technology.
1,273.207,68,1,1,38994801,10006,0,1,0,1,...,26136,37,1.1.1.1,53,192.168.1.137,4,UDP,1232,NOERROR,10006.1645522517.membrain-it.technology.
2,243.845,68,1,1,38994801,10015,0,1,0,1,...,45298,26,1.1.1.1,53,192.168.178.39,4,UDP,1232,NOERROR,10015.1645522517.membrain-it.technology.
3,361.843,68,1,1,38994801,10022,0,1,0,1,...,35295,22,1.1.1.1,53,10.71.6.153,4,UDP,1232,NOERROR,10022.1645522517.membrain-it.technology.
4,271.447,68,1,1,38994801,10046,0,1,0,1,...,19490,2,1.1.1.1,53,192.168.42.45,4,UDP,1232,NOERROR,10046.1645522516.membrain-it.technology.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3855,None,None,3,3,38995083,12454,None,None,None,None,...,None,67,192.168.50.1,53,2001:470:1f1b:e0:a2f3:c1ff:fec4:5e7b,4,TCP,None,None,None
3856,None,None,1,3,38995083,12466,None,None,None,None,...,None,69,10.1.254.254,53,None,4,TCP,None,None,None
3857,None,None,2,2,38995083,12501,None,None,None,None,...,None,30,10.0.0.1,53,2a02:908:1984:adb0:a2f3:c1ff:fec4:49ca,4,TCP,None,None,None
3858,314.166,68,1,3,38995083,12503,0,1,0,1,...,57207,112,46.19.96.50,53,192.168.1.10,4,TCP,4096,SERVFAIL,12503.1645525822.membrain-it.technology.
3859,534.332,68,2,3,38995083,12538,0,1,0,1,...,44731,63,75.75.75.75,53,10.0.0.108,4,TCP,512,SERVFAIL,12538.1645525828.membrain-it.technology.

In [ ]:
from ripe.atlas.sagan import DnsResult